### ISSUE TITLE
IDE不适配？

### ISSUE THREAD

**Issue by SmithGao** [dengzhi00/Live_Rtmp2#1]
您好 我最近手贱 下了AS 3.0 然后运行您的程序就报错 
Error:(75, 33) error: use of undeclared identifier 'malloc'
Error:(76, 34) error: use of undeclared identifier 'malloc'
Error:(151, 5) error: use of undeclared identifier 'free'
Error:(171, 29) error: use of undeclared identifier 'malloc'
Error:(175, 29) error: use of undeclared identifier 'malloc'
Error:(178, 13) error: use of undeclared identifier 'free'
Error:(179, 13) error: use of undeclared identifier 'free'

请问您的IDE是啥版本的？

**Comment by dengzhi00** [comment]
加上
#include <stdlib.h>
头文件就好了，新的里面有些不包含了

**Comment by dengzhi00** [comment]
@SmithGao 
加上
#include <stdlib.h>
头文件就好了，新的里面有些不包含了
